#!/usr/bin/env python3

import rosboard.two_way_mic_http.server



def run_server():
    # execute a python script asynchronously using subprocess popen
    # https://docs.python.org/3/library/asyncio-subprocess.html
    rosboard.two_way_mic_http.server.main(cert_file="ssl_keys/rosboard+3.pem", key_file="ssl_keys/rosboard+3-key.pem")
    #process = subprocess.Popen(["python3", "rosboard/two_way_mic_http/server.py"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)




run_server()





print("Running from %s" % str(rosboard.__path__))


# run rosboard.rosboard.main() and run server.py asynchronously



